apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: price-tracker
spec:
  podMetricsEndpoints:
  - path: /metrics
    port: metrics
  selector:
    matchLabels:
      app.kubernetes.io/component: price-tracker
